services:
  redis:
    image: redis:7-alpine
    container_name: whatsapp-bot-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    container_name: resume-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev123

volumes:
  redis-data: